version: "3.1"
services:
  app:
    build: .
    image: manologcode/api-podcast
    restart: always
    container_name: apipodcast
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
    ports:
        - "5002:5000"
    volumes:
        - ./app:/app
    environment:
      - API_TOKEN=your_super_secret_token # <-- REPLACE WITH A STRONG, UNIQUE TOKEN
