services:
  app:
    build: .
    image: manologcode/apipodcast
    restart: always
    container_name: apipodcast
    # command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
    ports:
        - "5002:5000"
    volumes:
        - ./app:/app
        - ./data:/app/data
    environment:
      - API_TOKEN=your_super_secret_token 
      - BASE_URL=http://192.168.1.69:5002
      - TITLE_PODCAST=Podcasts de Manolo Gomez
      - SUBTITLE_PODCAST=Mis ideas y experimentos convertidos en voz 
